package model;

import java.util.Date;

/**
 * TabKhinfo generated by MyEclipse - Hibernate Tools
 */

public class Orders  implements java.io.Serializable {


    // Fields    

     private String Comcode;
     private String Combewrite;
     private String Comprice;
     private String Comnum;
     private String Sprice;
     private String Finalprice;
     private Date Gooddate;
     private String Paytime;
     private Date Uplatedate;
     private String Supcode;
     private String Bank;
     private String AccountNum;


    // Constructors

    /** default constructor */
    public Orders() {
    }

	/** minimal constructor */
    public Orders(String Comcode) {
        this.Comcode = Comcode;
    }
    
    /** full constructor */
    public Orders(String Comcode, String Combewrite, String Comprice, String Comnum, String Sprice, String Finalprice, Date Gooddate, String Paytime, Date Uplatedate, String Supcode, String Bank, String AccountNum) {
        this.Comcode = Comcode;
        this.Combewrite = Combewrite;
        this.Comprice = Comprice;
        this.Comnum = Comnum;
        this.Sprice = Sprice;
        this.Finalprice = Finalprice;
        this.Gooddate = Gooddate;
        this.Paytime = Paytime;
        this.Uplatedate = Uplatedate;
        this.Supcode = Supcode;
        this.Bank = Bank;
        this.AccountNum = AccountNum;
    }

   
    // Property accessors

    public String getComcode() {
        return this.Comcode;
    }
    
    public void setComcode(String Comcode) {
        this.Comcode = Comcode;
    }

    public String getCombewrite() {
        return this.Combewrite;
    }
    
    public void setCombewrite(String Combewrite) {
        this.Combewrite = Combewrite;
    }

    public String getComprice() {
        return this.Comprice;
    }
    
    public void setComprice(String Comprice) {
        this.Comprice= Comprice;
    }

    public String getComnum() {
        return this.Comnum;
    }
    
    public void setComnum(String Comnum) {
        this.Comnum = Comnum;
    }

    public String getSprice() {
        return this.Sprice;
    }
    
    public void setSprice(String Sprice) {
        this.Sprice = Sprice;
    }

    public String getFinalprice() {
        return this.Finalprice;
    }
    
    public void setFinalprice(String Finalprice) {
        this.Finalprice = Finalprice;
    }

    public Date getGooddate() {
        return this.Gooddate;
    }
    
    public void setGooddate(Date Gooddate) {
        this.Gooddate = Gooddate;
    }

    public String getPaytime() {
        return this.Paytime;
    }
    
    public void setPaytime(String Paytime) {
        this.Paytime = Paytime;
    }

    public Date getUplatedate() {
        return this.Uplatedate;
    }
    
    public void setUplatedate(Date Uplatedate) {
        this.Uplatedate = Uplatedate;
    }

    public String getSupcode() {
        return this.Supcode;
    }
    
    public void setSupcode(String Supcode) {
        this.Supcode = Supcode;
    }

    public String getBank() {
        return this.Bank;
    }
    
    public void setBank(String Bank) {
        this.Bank = Bank;
    }

    public String getAccountNum() {
        return this.AccountNum;
    }
    
    public void setAccountNum(String AccountNum) {
        this.AccountNum = AccountNum;
    }
   








}